sudo: false

language: php

env:
  global:
    - COMPOSER_ROOT_VERSION="4.0.x-dev"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_DATABASE_CLASS="MySQLPDODatabase"
    - SS_ENVIRONMENT_TYPE="dev"
    - SS_DATABASE_NAME="test"
    - SS_DATABASE_PASSWORD="root"
    - SS_DATABASE_SERVER="localhost"
    - SS_DATABASE_USERNAME="root"

dist: trusty

matrix:
  include:
    - php: 7.0
      env: DB=MYSQL RECIPE_VERSION=1.1.x-dev PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=4.2.x-dev PHPUNIT_COVERAGE_TEST=1
    - php: 7.2
      env: DB=PGSQL RECIPE_VERSION=4.3.x-dev PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPUNIT_TEST=1

fast_finish: true

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - echo 'memory_limit = 3096M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - export PATH=~/.composer/vendor/bin:$PATH
      # Install composer dependencies
  - composer validate
  - composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o
  - composer require --no-update silverstripe/recipe-cms:$RECIPE_VERSION
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:2.1.x-dev; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/Pages; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml -vvv; fi
  - if [[ $PHPCS_TEST ]]; then   - DB_USER=root DB_PASSWD= vendor/bin/phpcs src/ tests/; fi
  
after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
