language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.6
    - php: 7.2

fast_finish: true

before_script:
  - phpenv rehash
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit --exclude-group exclude-from-travis; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml --exclude-group exclude-from-travis; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/; fi
